INFO:     2023-06-09 11:50:09,835 - Config loaded
INFO:     2023-06-09 11:50:09,836 - TelegramParser inited
INFO:     2023-06-09 11:50:09,836 - API: inited
INFO:     2023-06-09 11:50:09,845 - DataBase: creating database
INFO:     2023-06-09 11:50:09,846 - DataBase: database already exist
INFO:     2023-06-09 11:50:09,847 - DataBase: creating table
INFO:     2023-06-09 11:50:09,848 - DataBase: table already exist
INFO:     2023-06-09 11:50:09,848 - DataBase: inited
INFO:     2023-06-09 11:50:09,849 - Manager: inited
INFO:     2023-06-09 11:50:09,850 - Server: inited
INFO:     2023-06-09 11:50:09,850 - Finished inited process
INFO:     2023-06-09 11:50:09,850 - Starting threading
INFO:     2023-06-09 11:50:09,851 - Server: Starting
INFO:     2023-06-09 11:50:09,853 - Connecting to 149.154.167.51:443/TcpFull...
INFO:     2023-06-09 11:50:09,957 - Connection to 149.154.167.51:443/TcpFull complete!
INFO:     2023-06-09 11:50:10,548 - Parser: starting listening
INFO:     2023-06-09 11:50:48,424 - Parser: Getting post from channel postowl_test
ERROR:     2023-06-09 11:50:48,424 - Unhandled exception on func
Traceback (most recent call last):
  File "D:\IT-projects\PostOwl (Большие вызовы 22.23)\PostOwlMainServer\venv\Lib\site-packages\telethon\client\updates.py", line 543, in _dispatch_update
    await callback(event)
  File "D:\IT-projects\PostOwl (Большие вызовы 22.23)\PostOwlMainServer\parser.py", line 29, in func
    await handler(channel_name, message)
TypeError: object NoneType can't be used in 'await' expression
WARNING:     2023-06-09 12:14:06,729 - Server closed the connection: [WinError 64] Указанное сетевое имя более недоступно
WARNING:     2023-06-09 12:14:06,730 - Server closed the connection: [WinError 64] Указанное сетевое имя более недоступно
INFO:     2023-06-09 12:14:06,730 - Connection closed while receiving data
WARNING:     2023-06-09 12:14:06,730 - Server closed the connection: [WinError 64] Указанное сетевое имя более недоступно
INFO:     2023-06-09 12:14:06,730 - Closing current connection to begin reconnect...
INFO:     2023-06-09 12:14:06,730 - <class 'ConnectionResetError'> during disconnect: [WinError 64] Указанное сетевое имя более недоступно
INFO:     2023-06-09 12:14:06,731 - <class 'ConnectionResetError'> during disconnect: [WinError 64] Указанное сетевое имя более недоступно
INFO:     2023-06-09 12:14:06,731 - Connecting to 149.154.167.51:443/TcpFull...
INFO:     2023-06-09 12:14:06,901 - Connection to 149.154.167.51:443/TcpFull complete!
INFO:     2023-06-09 12:14:06,902 - Connection closed while receiving data
INFO:     2023-06-09 12:14:06,903 - Closing current connection to begin reconnect...
INFO:     2023-06-09 12:14:06,903 - Connection closed while sending data
INFO:     2023-06-09 12:14:06,904 - Connecting to 149.154.167.51:443/TcpFull...
INFO:     2023-06-09 12:14:07,151 - Connection to 149.154.167.51:443/TcpFull complete!
INFO:     2023-06-09 12:14:07,600 - Got difference for account updates
INFO:     2023-06-09 12:14:07,745 - Parser: Getting post from channel forbesrussia
ERROR:     2023-06-09 12:14:07,745 - Unhandled exception on func
Traceback (most recent call last):
  File "D:\IT-projects\PostOwl (Большие вызовы 22.23)\PostOwlMainServer\venv\Lib\site-packages\telethon\client\updates.py", line 543, in _dispatch_update
    await callback(event)
  File "D:\IT-projects\PostOwl (Большие вызовы 22.23)\PostOwlMainServer\parser.py", line 29, in func
    await handler(channel_name, message)
TypeError: object NoneType can't be used in 'await' expression
INFO:     2023-06-09 12:14:07,756 - Got difference for channel 1562812779 updates
INFO:     2023-06-09 12:14:07,981 - Got difference for channel 1756387595 updates
INFO:     2023-06-09 12:14:08,173 - Got difference for channel 1670606319 updates
INFO:     2023-06-09 12:15:12,877 - Disconnecting from 149.154.167.51:443/TcpFull...
INFO:     2023-06-09 12:15:12,878 - Disconnection from 149.154.167.51:443/TcpFull complete!
INFO:     2023-06-09 12:15:12,879 - Not disconnecting (already have no connection)
INFO:     2023-06-09 12:15:12,899 - Not disconnecting (already have no connection)
INFO:     2023-06-09 12:15:12,908 - Finishing process
